version: 2.1
jobs:
  test-node:
    executor: 
      name: node/default
      tag: '13'
    steps:
      - run:
          command: npm run test
  build-and-push:
      executor: docker/docker
      steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - docker/build:
            image: leinad502/tarea8
            tag: "latest,$CIRCLE_SHA1"
        - docker/push:
            image: leinad502/tarea8
            tag: "latest,$CIRCLE_SHA1"
orbs:
  docker: circleci/docker@1.4.0
workflows:  
    version: 2.1
    test:
      jobs:
        - test-node
        - build-and-push:
            requires:
              - testNode
   
