version: 2.1
jobs:
  testNode:
    - node/test
  build-and-push:
      executor: docker/docker
      steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - docker/build:
            image: leinad502/tarea8
            tag: "latest,$CIRCLE_SHA1"
        - docker/push:
            image: leinad502/tarea8
            tag: "latest,$CIRCLE_SHA1"
orbs:
  node: circleci/node@3.0.0
workflows:  
    version: 2.1
    test:
      jobs:
        - testNode
        - build-and-push:
            requires:
              - testNode
   
