version: 2.1
jobs:
  test:
    executor: node/node
    steps:
      - node/test
  build-and-push:
      executor: docker/docker
      steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - docker/build:
            image: leinad502/tarea8
            tag: "latest,$CIRCLE_SHA1"
        - docker/push:
            image: leinad502/tarea8
            tag: "latest,$CIRCLE_SHA1"
orbs:
  docker: circleci/docker@1.4.0
  node: circleci/node@3.0.0
workflows:  
    node-tests:
      jobs:
        - node/test:
            filters:
              branches:
                only:
                  - master
        - build-and-push:
            requires:
              - test
            filters:
              branches:
                only:
                  - master
   
