version: 2.1
jobs:
  test-node:
    executor: 
      name: circleci/node@3.0.0
    steps:
      - run:
          command: npm run test
  build-and-push:
      executor: docker/docker
      steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - docker/build:
            image: leinad502/tarea8
            tag: "latest,$CIRCLE_SHA1"
        - docker/push:
            image: leinad502/tarea8
            tag: "latest,$CIRCLE_SHA1"
orbs:
  docker: circleci/docker@1.4.0
workflows:  
    test:
      node-tests:
        - test-node
        - build-and-push:
            requires:
              - testNode
   
